### ISSUE TITLE
Show USD value of LP tokens on the review confirmation

### ISSUE THREAD

**Issue by alphastorm** [saddle-finance/saddle-frontend#270]

**Comment by hammeiam** [comment]
Hi @penandlim how is the USD value calculated? We just grab from coingecko for other tokens - would this be a weighted avg of pool coin values?

**Comment by alphastorm** [comment]
> Hi @penandlim how is the USD value calculated? We just grab from coingecko for other tokens - would this be a weighted avg of pool coin values?

Yeah I think that makes the most sense: `LP token value = total $ value of pool components / LP token supply`

**Comment by penandlim** [comment]
Yep that’s the most reasonable way.
