### ISSUE TITLE
[Design System] - Rewrite Placeholder

### ISSUE THREAD

**Issue by hammeiam** [saddle-finance/saddle-frontend#333]
- [ ] Define plan, components, and timeline
- [ ] Define theme structure
- [ ] Sync with Design Team
- [ ] Install styled-components
- [ ] Create / Refactor high-use components, including tests (Text, Layout, Spacing, Box, Img/Icon)
- [ ]  Create / Refactor derivative components, including tests (Button, Input, Checkbox, Advanced Options, Errors & Notifications)
- [ ] Create / Refactor other shared components, including tests  (Page, Modal, Nav)
- [ ] Remove Chakra
- [ ] Remove dead scss & theme

**Comment by ug02fast** [comment]
Seems outdated
