### ISSUE TITLE
[Testing] - Spike - Testnet deploy, CI integration testing

### ISSUE THREAD

**Issue by hammeiam** [saddle-finance/saddle-frontend#338]
Basically how do we get the cypress tests that we are currently running locally to run in a CI environment

- [x] Run against prod
- [ ] Run against an arbitrary branch
- [ ] Run with a testnet wallet
- [ ] How to test "no wallet" experience
- [ ] How to test custom scenarios like imbalanced  pools, new pools, guarded pool, etc

**Comment by alphastorm** [comment]
https://docs.github.com/en/actions/guides/about-service-containers
