### ISSUE TITLE
[Pool stats] - use graph to display 24h volume and APY for each pool

### ISSUE THREAD

**Issue by hammeiam** [saddle-finance/saddle-frontend#438]
- Use our graph (https://thegraph.com/explorer/subgraph/saddle-finance/saddle) to display 24h swap volume in USD. 
- Use the swap fees as a percent of the 24h volume to derive APY

**Comment by alphastorm** [comment]
Closed by https://github.com/saddle-finance/saddle-frontend/pull/479
