### ISSUE TITLE
Display the A parameter in the pool info section

### ISSUE THREAD

**Issue by alphastorm** [saddle-finance/saddle-frontend#485]
The amplification coefficient `A` should be included somewhere here, preferably with a tooltip that explains what it is:

![Screen Shot 2021-06-14 at 5 12 57 PM](https://user-images.githubusercontent.com/972382/121974227-cf4eb480-cd33-11eb-8d7e-26e3785df9ff.png)

**Comment by sandrasong** [comment]
Design is here: https://www.figma.com/file/hVhPxjcFcchzB9uFMpT4Fd/Saddle?node-id=807%3A487

David's PR looks good.
