### ISSUE TITLE
Allow users to click withdraw and play around with withdrawal options without a balance

### ISSUE THREAD

**Issue by alphastorm** [saddle-finance/saddle-frontend#501]
_NB_
quick product feedback/request: would be good to be able to click “withdraw” on the pools even if you don’t detect I have any LP shares. My alETH shares are currently staked, but it looks like there’s an arb opportunity to withdraw WETH, convert directly to alETH through the Alchemix contracts, then deposit the alETH. I’d love to play around with withdrawing various amounts of LP shares in WETH to see where the sweet spot is before I go through the hassle/cost of unstaking.

![image](https://user-images.githubusercontent.com/972382/122602112-2223b700-d027-11eb-9708-c735a2ce7839.png)

**Comment by Zor2040** [comment]
nice
