### ISSUE TITLE
Refactor web3 provider usage in the frontend

### ISSUE THREAD

**Issue by alphastorm** [saddle-finance/saddle-frontend#556]
Make sure we're using `ethers.providers.InfuraProvider` for production to get rid of extraneous `eth_chainId` calls (see: https://github.com/ethers-io/ethers.js/issues/901).  If we switch to using getDefaultProvider() everywhere and pass our API keys it should work out of the box.

**Comment by adijo** [comment]
Done in https://github.com/saddle-finance/saddle-frontend/pull/598
