### ISSUE TITLE
[Design / Design System / Style guide + Press Toolkit + Brand guidelines] Marketing Style Guide

### ISSUE THREAD

**Issue by darthbrooksiv** [saddle-finance/saddle-frontend#585]
Components and guidelines for marketing the Saddle brand

Includes:

- [x] Logomark, logotype layout and rules
- [x] Colorway (to be updated)
- [ ] Brand Voice and guidelines (Non blocking)
- [x] File/font repository
- [x] Digital guidelines (best case, worse case etc)
- [x] Swag _(skip this?)_

[EDIT]
- [ ] implement on docs (Zim)

The deliverable for this ticket is a downloadable press tool kit / brand kit that press or community contributors can access from our website

Example: https://www.notion.so/Media-Kit-138cca20324d4767b4e18f475ad19412 
[/EDIT]

link to Figma doc: https://www.figma.com/file/hVhPxjcFcchzB9uFMpT4Fd/?node-id=1892%3A65727
link to marketing requests: https://docs.google.com/document/d/1YX_wgMX-GibnhzUHJ4PjFPpPhSeL5FRVqVvjEpp-ob4/edit#heading=h.f116mts0wukl

**Comment by zimh** [comment]
JFYI closing this original issue https://github.com/saddle-finance/tickets/issues/108 

The deliverable for this ticket is a downloadable press tool kit / brand kit that press or community contributors can access from our website

- [ ] implement on website (Zim)

**Comment by darthbrooksiv** [comment]
Links to files and layout https://www.figma.com/file/04BYdqGGsC3xXZLkfs2eYs/?node-id=1%3A14896

Prep files:
- [ ] SVG
- [ ] PNG
any other doc requirements (@zimh)?

**Comment by zimh** [comment]
Can you ping me @darthbrooksiv when you have download link and I'll add it to our docs

**Comment by darthbrooksiv** [comment]
@zimh logo files are here: https://drive.google.com/drive/folders/1MJqRHkVkFRFitWS2AG8k5B4T45Gcv9kl?usp=sharing

the zipped file has all pngs, svgs and the guidelines
