### ISSUE TITLE
[EIP-1559] Add better 1559 gas support

### ISSUE THREAD

**Issue by hammeiam** [saddle-finance/saddle-frontend#612]
- [x] Sign up for blocknative ($100/mo plan should be fine)
- [ ] add an endpoint to serve blocknative gas responses
- [ ] update UI to account for new gas logic (eg base fee is opaque, you only choose priority fee)

Us not explicitly supporting 1559 has caused some issues for users

**Comment by ug02fast** [comment]
Offloaded to MetaMask
