### ISSUE TITLE
[Design / Design System / Components] Design and build components

### ISSUE THREAD

**Issue by zimh** [saddle-finance/saddle-frontend#632]
Ref components list: https://docs.google.com/spreadsheets/d/1pYJgm1yhrBcedfqYcBFyqaFQZQECjnjUowuDol0qAqs/edit#gid=381250160 

Navigation Link
- [x] Design completed
- [ ] Build completed

Saddle Logo
- [x] Design completed
- [ ] Build completed

Address
- [x] Design completed
- [ ] Build completed

Theme Switch
- [ ] Design completed
- [ ] Build completed

Title
- [ ] Design completed
- [ ] Build completed

Token Icon
- [ ] Design completed
- [ ] Build completed

Token Input
- [ ] Design completed
- [ ] Build completed

Token selection item
- [ ] Design completed
- [ ] Build completed

Tooltip
- [ ] Design completed
- [ ] Build completed

Toggle box
- [ ] Design completed
- [ ] Build completed

Radio button
- [ ] Design completed
- [ ] Build completed

Transaction info
- [ ] Design completed
- [ ] Build completed

Advanced option
- [ ] Design completed
- [ ] Build completed

Pool tokens array
- [ ] Design completed
- [ ] Build completed

Tag
- [ ] Design completed
- [ ] Build completed

Pool filter tab
- [ ] Design completed
- [ ] Build completed

Info text ?
- [ ] Design completed
- [ ] Build completed

**Comment by ug02fast** [comment]
outdated and solved with mUI
