### ISSUE TITLE
[Design / Governance / Token claim UI] Implement token claim UI

### ISSUE THREAD

**Issue by zimh** [saddle-finance/saddle-frontend#635]
Ref: https://www.figma.com/file/zpjfF2KnLIrTeeAl44Y9bA/Saddle-Design?node-id=1711%3A48353

Do we have specs for this feature? / Do we need to spec this out more?

**Comment by sandrasong** [comment]
Mike has been working on the visual of this UI, the most updated style is here:
https://www.figma.com/file/04BYdqGGsC3xXZLkfs2eYs/Design-System?node-id=12%3A9404

@darthbrooksiv  Would you like to put specs for this UI?

**Comment by darthbrooksiv** [comment]
Token Claim UI (Day/Night) 

link to files: https://www.figma.com/file/zpjfF2KnLIrTeeAl44Y9bA/?node-id=1711%3A48353
