### ISSUE TITLE
[Design System] Input Field Component 

### ISSUE THREAD

**Issue by darthbrooksiv** [saddle-finance/saddle-frontend#651]
Build Input Field Component, link to design files: https://www.figma.com/file/04BYdqGGsC3xXZLkfs2eYs/?node-id=1%3A21353

- [ ] Create an Empty Story in Storybook.js for input field component
- [ ] API Design (in Git comments)

1. Input Field 
- [ ] default State
- [ ] filled State
- [ ] error State

*Review
- [ ] Unit Test
- [ ] Design review

2. Label State
- [ ] none
- [ ] right aligned
- [ ] left aligned
- [ ] left and right aligned

3. Non Selectable state
- [ ] Default

*Review
- [ ] Unit Test  
- [ ] developer review 
- [ ] design review

**Comment by ug02fast** [comment]
outdated and solved with mUI
