### ISSUE TITLE
CORS issues getting prices

### ISSUE THREAD

**Issue by mhluongo** [saddle-finance/saddle-frontend#674]
![Screenshot from 2021-10-13 11-14-31](https://user-images.githubusercontent.com/427505/137162530-7945ca4c-ddb6-41ec-a284-e0a0e66b4bfe.png)

Loading [the main page](https://saddle.exchange/#/pools) on Firefox gives a slew of CORS errors, preventing some prices from being shown.

**Comment by ug02fast** [comment]
no longer happening
