### ISSUE TITLE
[Website] Update b4b page with info on deputies/judges

### ISSUE THREAD

**Issue by zimh** [saddle-finance/saddle-frontend#688]
Copy is here: https://docs.google.com/document/d/1liI8yz5PHM48gv2Y0muD9AzFwOdbbKq9h6pM_ncycGw/edit#heading=h.hjsg3zjiqpb6

~Optionally we can have stylized portraits of each of the deputies (would be a nice lil gift), otherwise~ let's just use their TW bio photo

- [x] Designs using attached copy (Sandra)
- [ ] ~[Optional] add stylized portraits for each of the deputies~
- [x] Stakeholder review (Zim)
- [x] Implement and generate preview (Nikita)
- [x] Stakeholder sign-off (Zim)

Project/ticket owner: Sandra
Requested delivery by 11/15

**Comment by sandrasong** [comment]
Figma file: https://www.figma.com/file/QwGOmtwq7H50h9TqOKPR66/?node-id=2%3A319

![Screen Shot 2021-11-11 at 2 49 48 PM](https://user-images.githubusercontent.com/11672986/141360299-565daa0f-cc66-47cb-b3dd-ea8f89c2c57f.png)

![Screen Shot 2021-11-11 at 2 54 14 PM](https://user-images.githubusercontent.com/11672986/141360394-6decfb5f-076d-465b-bd0b-4a89002849ea.png)
