### ISSUE TITLE
[dApp / bug] Withdraw page side modal missing section dividers + background image?

### ISSUE THREAD

**Issue by zimh** [saddle-finance/saddle-frontend#691]
This is the deposit page (header nav > Pools > click any `deposit` button):
![image](https://user-images.githubusercontent.com/19593719/140940204-7884d443-41c6-44b9-b3c8-721750701fc9.png)

This is the withdraw page: (header nav > Pools > click any `withdraw` button):
![Screen Shot 2021-11-09 at 9 16 20 AM](https://user-images.githubusercontent.com/19593719/140940323-3f4e9eb1-3e2f-4760-8b08-d2b4c73a6015.png)

Notice:
* Right panel/modal, deposit page has red line separating sections, whereas withdraw page does not have this.
* Deposit page has seahorse in background, withdraw page does not have this

Rec fix:
* withdraw page should have red line separating all side panel/modal sections (between My Shares (not shown in screenshots) and NAME Pool, and then Currency reserves) -- basically make withdraw page side panel layout same as deposit page layout
* withdraw page should have same seahorse in bg as deposit page

**Comment by ug02fast** [comment]
https://github.com/saddle-finance/saddle-frontend/pull/692
