### ISSUE TITLE
Update Arbitrum reward logic

### ISSUE THREAD

**Issue by hammeiam** [saddle-finance/saddle-frontend#746]
As per this thread (https://saddle-finance.slack.com/archives/C02P1QQ1JBU/p1640182198014800):

- SDL rewards are not claimable on arbitrum
- The SDL retroactive airdrop was only for mainnet
- The claim UI on Arbitrum is just meant to be a preview of SDL rewards

Given this, we want to:
- Disable claiming rewards on Arbitrum, but still show users the rewards that are accumulating
- Add info clearly explaining the situation. Something like "SDL is currently only deployed on Ethereum Mainnet and is not yet claimable on this chain. We display the amount that will be claimable once SDL is available on this network. See this post for more information." cc zim for faq link
- Possibly hide the retro airdrop section on arbitrum, though it should be 0 anyway since the retro contract doesn't exist on that chain

**Comment by zimh** [comment]
FAQ added https://docs.saddle.finance/saddle-faq#why-cant-i-claim-my-sdl-on-arbitrum
