### ISSUE TITLE
Gas estimate for swap showing 0

### ISSUE THREAD

**Issue by zimh** [saddle-finance/saddle-frontend#755]
<img width="565" alt="Screen Shot 2021-12-31 at 4 29 08 PM" src="https://user-images.githubusercontent.com/19593719/147839367-4a19f51e-cbe6-4535-ba1e-f8c72c7e7d0c.png">

should show correct gas estimate or just remove from UI altogether

**Comment by ug02fast** [comment]
https://github.com/saddle-finance/saddle-frontend/pull/758
