### ISSUE TITLE
[Spike] xChain notifications

### ISSUE THREAD

**Issue by hammeiam** [saddle-finance/saddle-frontend#785]
right now bnc notifications only works on mainnet, which doesn't jive with a multichain future. Consider switching back to toasts, or using a MUI solution for the UI. Maybe do something like Sushi does and store txn hashes in state to periodically look up their status. https://github.com/sushiswap/sushiswap-interface/blob/canary/src/hooks/useTransactionStatus.ts

**Comment by ug02fast** [comment]
A follow-up to the issue.

Currently, the Saddle app is using a library called `bnc-notify` for transaction status toasts which does not support all the networks that we're deployed on. This results in toasts not working when transactions are executed on those networks.

Investigating the `bnc-notify` code to see if it's possible to consume new chainIds without too much rework would make the most sense to try first as that would require the least amount of work and diverge least from our current UX.

Spiking on what other DeFi tools are doing for notifications will give a good sense of the best possible solution.

Creating a new solution to notifications will result in more maintenance from devs compared with using our current notification library. Building a new solution will give us more flexibility and control over what and how notifications are displayed from size to positioning to animations.

One potential solution is to leverage mUI's Snackbar component https://mui.com/components/snackbars/ for the UI piece. To manage state, a React Provider can be used to feed all transaction details into which will ultimately trigger the Snackbar component showing and hiding. Another good solution is what @hammeiam mentioned, using a solution similar to SushiSwap.

**Comment by hammeiam** [comment]
Here is the list of [supported network](https://docs.blocknative.com/supported-networks)s for bnc-notify. Mainnet and BSC are the only ones that offer us coverage, which means we're missing Optimism, Arbitrum, Fantom, and soon Moon[x]. Plus local hardhat. 

I also like how in their docs, bnc calls out that they offer different features for different networks, and I think we can do the same. So P0 is `confirmed/failed` for txns, P1 is `sent/canceled`, P2 is `speedup` etc. so we can iteratively improve it. 

I think we can't rely on bnc-notify to offer us the coverage we need for our notifications, but maybe we can copy/paste an existing solution from Sushi/Uni/ohm/yearn or other open reputable dapps

**Comment by ug02fast** [comment]
The implementation of a new solution should take approximately 2 weeks. 1 week to integrate the state management and web3 API and 1 week to build the UI and test across all the networks. If integrating a solution similar to Sushi's takes too much rewrite of the Saddle app then a custom solution will have to be created.
