### ISSUE TITLE
npm run postinstalll command don't work on the windows.

### ISSUE THREAD

**Issue by nkrulikovsky** [saddle-finance/saddle-frontend#847]
On windows, ` "postinstall": "typechain --target ethers-v5 'src/constants/abis/*.json'"` don't work because windows git shell don't support single quote for glob.
![image](https://user-images.githubusercontent.com/75422800/154483750-62ba1723-4a06-42d5-989f-f8b85775e9b0.png)

![image](https://user-images.githubusercontent.com/75422800/154483684-98082fa2-4ba2-4eba-a190-9209f231cf02.png)

**Comment by ug02fast** [comment]
My install and build works fine on Windows. It could be a matter of installing the modules correctly with npm.
