### ISSUE TITLE
WalletConnect connector not showing qrcode

### ISSUE THREAD

**Issue by hammeiam** [saddle-finance/saddle-frontend#852]
Users reporting that WalletConnect connector not displaying qrcode, which breaks the experience for them

**Comment by 0xlenin** [comment]
grumblings getting louder. maybe p0 since users ostensibly can't withdraw funds if they use walletconnect?

<img width="898" alt="image" src="https://user-images.githubusercontent.com/100043472/155404778-6dcdd0e8-e3ad-40ab-983d-68251bc961ff.png">

**Comment by Karthik-Gupta** [comment]
Looks like this issue has resurfaced. More details on the behaviour:
* OnClick of WalletConnect -> No QR code box is popped open, nothing happens
* OnClick of Coinbase Wallet -> QR code doesn't load, it shows 'Connecting.' indefinitely and also the pop-up gets stuck, can not close it

![image](https://user-images.githubusercontent.com/28344126/158366214-d5337f58-35c7-4b4f-add2-94d059c63c5a.png)

**Comment by ug02fast** [comment]
> Looks like this issue has resurfaced. More details on the behaviour:
> 
> * OnClick of WalletConnect -> No QR code box is popped open, nothing happens
> * OnClick of Coinbase Wallet -> QR code doesn't load, it shows 'Connecting.' indefinitely and also the pop-up gets stuck, can not close it
> 
> ![image](https://user-images.githubusercontent.com/28344126/158366214-d5337f58-35c7-4b4f-add2-94d059c63c5a.png)

Fix merged and should be live shortly.
