### ISSUE TITLE
Find solution for batching multicalls

### ISSUE THREAD

**Issue by hammeiam** [saddle-finance/saddle-frontend#932]
The multicall contract can only do a finite number of calls in one go. Look in existing repos (uniswap, cowswap etc) for the hook or function that they use to split large multicall requests into batches. We should be able to copy paste instead of writing our own logic.

Eg let's say that the multicall contract can't make more than 20 requests before it this a block gasLimit, but we have 40 calls to multicall. I want a function that splits those 40 calls into 2 separate multicalls, then combines the result.

```javascript
calls = Array(40).fill(someCallData)
results = await (requestMulticall(calls){
   MAX_CALLS = 20
  chunks = createChunks(calls, MAX_CALLS)
  // would be nice to have some retry logic here
  results = Promise.all(chunks.map(chunk => multicallContract.multicall(chunk))
  return results.flatten()
})(calls)
assert results.length === 40
```

**Comment by ug02fast** [comment]
@hammeiam completed
