### ISSUE TITLE
Move tokenIcon references from TOKENS_MAP object to a static resource reference

### ISSUE THREAD

**Issue by hammeiam** [saddle-finance/saddle-frontend#953]
Currently our tokens look like this:
```javascript
import usdcLogo from "../assets/icons/usdc.svg"

const USDC_TOKEN = {
  symbol: "USDC"
  icon: usdcLogo
}
```

I would like to remove the `icon` attribute from the token object, and instead refer to the static asset directly eg
```javascript
<img src={`{assetPath}/{token.symbol.toLowerCase()}.svg`} />
```

This will require:
- renaming all token assets to lowercase token symbols
- making sure all tokens have the same extension (svg vs png)
- changing references from `token.icon` to `assetPath/token.symbol`
- removing `icon` from the token definition
- preferably, displaying a fallback grey circle if that token asset isn't found

(assigned to both art and Duy, communicate about who has a free cycle to take this. Should take maybe 1.5 days)

**Comment by ug02fast** [comment]
closed by: #964
